spring:
  application:
    name: consul-demo-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
